version: "3.0"
services:
  webserver:
    image: shinyorke/airflow:latest
    container_name: airflow_webserver
    env_file: env_example
    ports:
      - "80:8080"
    restart: always
    command: ["webserver", "init"]
networks:
  default:
    external:
      name: airflow_link